/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libr;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Amr Hossam
 */
public class searchm extends javax.swing.JFrame {

    Connection c = libr.DBc.DBCon();
    PreparedStatement st = null;
    ResultSet rs;
    String name;
    int co = 0;
    ArrayList<String> mid = new ArrayList();
    ArrayList<String> bid = new ArrayList();
    final DefaultListModel<String> model = new DefaultListModel<>();
    public searchm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberinfo = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        pnumber = new javax.swing.JLabel();
        nid = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        borrowed = new javax.swing.JLabel();
        fan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        borrowedframe = new javax.swing.JDialog();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Bname = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Bid = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Btype = new javax.swing.JLabel();
        Bauthor = new javax.swing.JLabel();
        Bp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FANCLUBS = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        FAN1 = new javax.swing.JLabel();
        FAN2 = new javax.swing.JLabel();
        FAN3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        results = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        s = new javax.swing.JComboBox<>();
        sm = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        b = new javax.swing.JButton();
        booki = new javax.swing.JButton();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(34, 54, 113));

        jLabel5.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MEMBER's INFO");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5))
        );

        jLabel6.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel6.setText("Number of borrowed books :");

        jLabel7.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel7.setText("Email :");

        jLabel8.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel8.setText("National ID :");

        jLabel9.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel9.setText("Phone Number :");

        jLabel13.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel13.setText("Name :");

        jLabel14.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel14.setText("ID :");

        id.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        Name.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        pnumber.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        nid.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        email.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        borrowed.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        fan.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(34, 54, 113));
        jButton1.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Borrowed BOOKS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(34, 54, 113));
        jButton2.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Show Fan CLUBS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(146, 146, 146)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(fan, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(71, 71, 71))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(borrowed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(pnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(borrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fan, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout memberinfoLayout = new javax.swing.GroupLayout(memberinfo.getContentPane());
        memberinfo.getContentPane().setLayout(memberinfoLayout);
        memberinfoLayout.setHorizontalGroup(
            memberinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        memberinfoLayout.setVerticalGroup(
            memberinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(34, 54, 113));
        jLabel16.setText("BOOK's Name :");

        Bname.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        Bname.setForeground(new java.awt.Color(34, 54, 113));

        next.setBackground(new java.awt.Color(34, 54, 113));
        next.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(34, 54, 113));
        back.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Bid.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        Bid.setForeground(new java.awt.Color(34, 54, 113));

        jLabel17.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(34, 54, 113));
        jLabel17.setText("BOOK's ID :");

        jLabel20.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(34, 54, 113));
        jLabel20.setText("BOOK's Type :");

        jLabel21.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(34, 54, 113));
        jLabel21.setText("BOOK's Author :");

        jLabel22.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(34, 54, 113));
        jLabel22.setText("BOOK's Publisher :");

        Btype.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        Btype.setForeground(new java.awt.Color(34, 54, 113));

        Bauthor.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        Bauthor.setForeground(new java.awt.Color(34, 54, 113));

        Bp.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        Bp.setForeground(new java.awt.Color(34, 54, 113));

        jPanel2.setBackground(new java.awt.Color(34, 54, 113));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Borrowed BOOKS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next)
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel20))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(Btype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(Bauthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(Bp, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bauthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(next))
                .addContainerGap())
        );

        javax.swing.GroupLayout borrowedframeLayout = new javax.swing.GroupLayout(borrowedframe.getContentPane());
        borrowedframe.getContentPane().setLayout(borrowedframeLayout);
        borrowedframeLayout.setHorizontalGroup(
            borrowedframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        borrowedframeLayout.setVerticalGroup(
            borrowedframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        FAN1.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        FAN1.setForeground(new java.awt.Color(34, 54, 113));

        FAN2.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        FAN2.setForeground(new java.awt.Color(34, 54, 113));

        FAN3.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        FAN3.setForeground(new java.awt.Color(34, 54, 113));

        jPanel3.setBackground(new java.awt.Color(34, 54, 113));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Joined Fan CLUBS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel15))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FAN3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FAN1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FAN2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FAN1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FAN2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FAN3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FANCLUBSLayout = new javax.swing.GroupLayout(FANCLUBS.getContentPane());
        FANCLUBS.getContentPane().setLayout(FANCLUBSLayout);
        FANCLUBSLayout.setHorizontalGroup(
            FANCLUBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FANCLUBSLayout.setVerticalGroup(
            FANCLUBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        results.setFont(new java.awt.Font("Prototype", 0, 28)); // NOI18N
        results.setForeground(new java.awt.Color(34, 54, 113));
        jScrollPane1.setViewportView(results);

        jPanel5.setBackground(new java.awt.Color(34, 54, 113));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MAIN MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        s.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        s.setForeground(new java.awt.Color(51, 51, 51));
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "National ID", "Phone Number", "Email" }));

        sm.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(34, 54, 113));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search Ror a MEMBER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10))
        );

        jLabel24.setFont(new java.awt.Font("Prototype", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(34, 54, 113));
        jLabel24.setText("Results :");

        jLabel25.setFont(new java.awt.Font("Prototype", 0, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(34, 54, 113));
        jLabel25.setText("Search By :");

        b.setBackground(new java.awt.Color(34, 54, 113));
        b.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("Search");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        booki.setBackground(new java.awt.Color(34, 54, 113));
        booki.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        booki.setForeground(new java.awt.Color(255, 255, 255));
        booki.setText("Show Book's Info :");
        booki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(booki, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(sm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addComponent(booki, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String fan1,fan2,fan3;int bc,indx;
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        indx++;

        if(indx==(bc-1)){
            next.setVisible(false);
        }

        else if(bc==0){
            JOptionPane.showMessageDialog(null, "MEMBER HAS NO BORROWED BOOKS");
        }
        if(indx>0){
            back.setVisible(true);
        }
        try {
            st = c.prepareStatement("SELECT books.BOOK_ID,books.BOOK_NAME,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.BOOK_STOCK FROM books,book_type,book_author,book_publisher WHERE BOOK_ID = ? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID) AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) ORDER BY BOOK_ID");
            st.setString(1, bid.get(indx));
            rs = st.executeQuery();
            while(rs.next()){
                Bname.setText(rs.getString("BOOK_ID"));
                Bid.setText(rs.getString("BOOK_NAME"));
                Btype.setText(rs.getString("TYPE"));
                Bauthor.setText(rs.getString("AUTHOR"));
                Bp.setText(rs.getString("PUBLISHER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        indx--;

        next.setVisible(true);
        if(indx==0){
            back.setVisible(false);
        }

        else if(bc==0){
            JOptionPane.showMessageDialog(null, "MEMBER HAS NO BORROWED BOOKS");
        }

        try {
            st = c.prepareStatement("SELECT books.BOOK_ID,books.BOOK_NAME,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.BOOK_STOCK FROM books,book_type,book_author,book_publisher WHERE BOOK_ID = ? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID) AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) ORDER BY BOOK_ID");
            st.setString(1, bid.get(indx));
            rs = st.executeQuery();
            while(rs.next()){
                Bname.setText(rs.getString("BOOK_ID"));
                Bid.setText(rs.getString("BOOK_NAME"));
                Btype.setText(rs.getString("TYPE"));
                Bauthor.setText(rs.getString("AUTHOR"));
                Bp.setText(rs.getString("PUBLISHER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_backActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        (mainm.sm).setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed

        if(s.getSelectedIndex() == 0){
            results.setModel(model);
            model.removeAllElements();
            mid.clear();
            try{
                Integer.parseInt(sm.getText());
            }catch (NumberFormatException ee){
                JOptionPane.showMessageDialog(this, "Enter a valid ID!");
            }
            name = sm.getText();
            try {
                st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_ID = ?");
                st.setString(1, name);
                rs = st.executeQuery();
                co = 0;
                while(rs.next()){
                    model.addElement(rs.getString("MEMBER_NAME")+" ("+rs.getString("MEMBER_ID")+")");
                    mid.add(co, rs.getString("MEMBER_ID"));
                    co++;
                }
                if(co==0){
                    JOptionPane.showMessageDialog(this, "No Result!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
            }}
            else if(s.getSelectedIndex() == 1){
                results.setModel(model);
                model.removeAllElements();
                mid.clear();

                name = sm.getText();

                try {
                    st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_Name = ?");
                    st.setString(1, name);
                    rs = st.executeQuery();
                    co = 0;
                    while(rs.next()){
                        model.addElement(rs.getString("MEMBER_NAME")+" ("+rs.getString("MEMBER_ID")+")");
                        mid.add(co, rs.getString("MEMBER_ID"));
                        co++;
                    }
                    if(co==0){
                        JOptionPane.showMessageDialog(this, "No Result!");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
                }}
                else if(s.getSelectedIndex() == 2){
                    results.setModel(model);
                    model.removeAllElements();
                    mid.clear();
                    try{
                        Double.parseDouble(sm.getText());
                    }catch (NumberFormatException ee){
                        JOptionPane.showMessageDialog(null, "Enter a valid national ID!");
                    }
                    name = sm.getText();
                    try {
                        st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_NID = ?");
                        st.setString(1, name);
                        rs = st.executeQuery();
                        co = 0;
                        while(rs.next()){
                           model.addElement(rs.getString("MEMBER_NAME")+" ("+rs.getString("MEMBER_ID")+")");
                           mid.add(co, rs.getString("MEMBER_ID"));
                            co++;
                        }
                        if(co==0){
                            JOptionPane.showMessageDialog(this, "No Result!");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
                    }}
                    else if(s.getSelectedIndex() == 3){
                        results.setModel(model);
                        model.removeAllElements();
                        mid.clear();
                        try{
                            Integer.parseInt(sm.getText());
                        }catch (NumberFormatException ee){
                            JOptionPane.showMessageDialog(this, "Enter a valid phone number!");
                        }
                        name = sm.getText();

                        if(name.length()!=11||!name.startsWith("01")){
                            JOptionPane.showMessageDialog(this, "Enter a valid phone number!");
                            //cant add break!!!!
                        }

                        try {
                            st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_PNUMBER = ?");
                            st.setString(1, name);
                            rs = st.executeQuery();
                            co = 0;
                            while(rs.next()){
                                model.addElement(rs.getString("MEMBER_NAME")+" ("+rs.getString("MEMBER_ID")+")");
                                mid.add(co, rs.getString("MEMBER_ID"));
                                co++;
                            }
                            if(co==0){
                                JOptionPane.showMessageDialog(this, "No Result!");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
                        }}
                        else if(s.getSelectedIndex() == 4){
                            results.setModel(model);
                            model.removeAllElements();
                            mid.clear();

                            name = sm.getText();

                            try {
                                st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_EMAIL = ?");
                                st.setString(1, name);
                                rs = st.executeQuery();
                                co = 0;
                                while(rs.next()){
                                   model.addElement(rs.getString("MEMBER_NAME")+" ("+rs.getString("MEMBER_ID")+")");
                                   mid.add(co, rs.getString("MEMBER_ID"));
                                    co++;
                                }
                                if(co==0){
                                    JOptionPane.showMessageDialog(this, "No Result!");
                                }
                            } catch (SQLException ex) {
                                Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
                            }}
    }//GEN-LAST:event_bActionPerformed

    private void bookiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookiActionPerformed
        if(co == 0){
            JOptionPane.showMessageDialog(this, "PLEASE SELECTE A RESULT!");
        }else{
            memberinfo.setVisible(true);
            memberinfo.setBounds(500, 400, 700, 470);
            try {
                st = c.prepareStatement("SELECT * FROM `members` WHERE MEMBER_ID = ?");
                st.setString(1, mid.get(results.getSelectedIndex()));
                rs = st.executeQuery();
                int temp;

                while(rs.next()){
                    mID = rs.getString("MEMBER_ID");
                    id.setText(mID);
                    Name.setText(rs.getString("MEMBER_NAME"));
                    email.setText(rs.getString("MEMBER_EMAIL"));
                    nid.setText(rs.getString("MEMBER_NID"));
                    pnumber.setText(rs.getString("MEMBER_PNUMBER"));
                    borrowed.setText(rs.getString("BORROWED"));
                    temp=rs.getInt("FAN_C");
                    if(temp==0){
                        fan.setText("Not in a fan club yet");
                    }
                    else{
                        fan.setText("No. of joined fan clubs: "+temp);
                        fan1=rs.getString("FAN_1");
                        fan2=rs.getString("FAN_2");
                        fan3=rs.getString("FAN_3");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_bookiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       indx=0;
       L1:{
        try {
            st = c.prepareStatement("SELECT * FROM `lend` WHERE `M_ID` = ?");
            st.setString(1, mid.get(results.getSelectedIndex()));
            rs = st.executeQuery();
            indx=0;
            while(rs.next()){
                bid.add(rs.getString("B_ID"));
            }
            bc=bid.size();
            if(indx==0){
                back.setVisible(false);
            }
            if(bc==1){
                next.setVisible(false);
            }
            else if(bc==0){
                JOptionPane.showMessageDialog(null, "MEMBER HAS NO BORROWED BOOKS");
                back.setVisible(false);
                next.setVisible(false);
                break L1;
            }
            borrowedframe.setVisible(true);
            borrowedframe.setBounds(500, 400, 700, 370);
            st = c.prepareStatement("SELECT books.BOOK_ID,books.BOOK_NAME,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.BOOK_STOCK FROM books,book_type,book_author,book_publisher WHERE BOOK_ID = ? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID) AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) ORDER BY BOOK_ID");
            st.setString(1, bid.get(indx));
            rs = st.executeQuery();
            while(rs.next()){
                Bname.setText(rs.getString("BOOK_ID"));
                Bid.setText(rs.getString("BOOK_NAME"));
                Btype.setText(rs.getString("TYPE"));
                Bauthor.setText(rs.getString("AUTHOR"));
                Bp.setText(rs.getString("PUBLISHER"));
            }
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(searchm.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton1ActionPerformed
    String mID;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        L2:{
            try{
            st = c.prepareStatement("SELECT * FROM MEMBERS WHERE MEMBER_ID = ?");
            st.setString(1, mID);
            rs = st.executeQuery();
            while(rs.next()){
                if("1".equals(rs.getString("FAN_1")) && "1".equals(rs.getString("FAN_2")) && "1".equals(rs.getString("FAN_3"))){
                    JOptionPane.showMessageDialog(null, "THE Member is NOT in a CLUB yet!", "ERROR",2);
                    break L2;
                }
            }
            }catch (SQLException ex) {
            Logger.getLogger(searchm.class.getName()).log(Level.SEVERE, null, ex);
        }
            try {
            st = c.prepareStatement("SELECT * FROM `fanclub` WHERE `CLUB_ID` = ?");

            FANCLUBS.setVisible(true);
            FANCLUBS.setBounds(500, 400, 700, 300);
            String temp;
            st.setString(1, fan1);
            rs = st.executeQuery();
            rs.next();
            temp=rs.getString("CLUB_NAME");
            if(!temp.equalsIgnoreCase("DEFAULT")){
            FAN1.setText(temp);}
            st.setString(1, fan2);
            rs = st.executeQuery();
            rs.next();
            temp=rs.getString("CLUB_NAME");
            if(!temp.equalsIgnoreCase("DEFAULT")){
            FAN2.setText(temp);}
            st.setString(1, fan3);
            rs = st.executeQuery();
            rs.next();
            temp=rs.getString("CLUB_NAME");
            if(!temp.equalsIgnoreCase("DEFAULT")){
            FAN3.setText(temp);}

        }catch (SQLException ex) {
            Logger.getLogger(searchm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bauthor;
    private javax.swing.JLabel Bid;
    private javax.swing.JLabel Bname;
    private javax.swing.JLabel Bp;
    private javax.swing.JLabel Btype;
    private javax.swing.JLabel FAN1;
    private javax.swing.JLabel FAN2;
    private javax.swing.JLabel FAN3;
    private javax.swing.JDialog FANCLUBS;
    private javax.swing.JLabel Name;
    private javax.swing.JButton b;
    private javax.swing.JButton back;
    private javax.swing.JButton booki;
    private javax.swing.JLabel borrowed;
    private javax.swing.JDialog borrowedframe;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fan;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog memberinfo;
    private javax.swing.JButton next;
    private javax.swing.JLabel nid;
    private javax.swing.JLabel pnumber;
    private javax.swing.JList<String> results;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JTextField sm;
    // End of variables declaration//GEN-END:variables
}
