/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libr;
import com.mysql.cj.xdevapi.Result;
import com.mysql.cj.xdevapi.Statement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Yaseen
 */
public class searchc extends javax.swing.JFrame {
    Connection c = libr.DBc.DBCon();
    PreparedStatement st = null;
    ResultSet rs;
    String name;
    int co = 0;
    ArrayList<String> bidi = new ArrayList();
    final DefaultListModel<String> model1 = new DefaultListModel<>();
    /**
     * Creates new form searchc
     */
    public searchc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dia1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reslist = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s = new javax.swing.JComboBox<>();
        b = new javax.swing.JButton();
        sb = new javax.swing.JTextField();
        Bclubinfo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(34, 54, 113));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CLUB's INFO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        l1.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(34, 54, 113));
        l1.setText("CLUB's Name :");

        l3.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l3.setForeground(new java.awt.Color(34, 54, 113));
        l3.setText("CLUB's Admin :");

        l8.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l8.setForeground(new java.awt.Color(34, 54, 113));
        l8.setText("Book ID :");

        l7.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l7.setForeground(new java.awt.Color(34, 54, 113));
        l7.setText("Book name :");

        l5.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l5.setForeground(new java.awt.Color(34, 54, 113));
        l5.setText("Admin's E-mail :");

        l12.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l12.setForeground(new java.awt.Color(34, 54, 113));
        l12.setText("Book type :");

        l9.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l9.setForeground(new java.awt.Color(34, 54, 113));
        l9.setText("Book author :");

        l10.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l10.setForeground(new java.awt.Color(34, 54, 113));
        l10.setText("Book publisher :");

        l11.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l11.setForeground(new java.awt.Color(34, 54, 113));
        l11.setText("Book rating :");

        l6.setFont(new java.awt.Font("Prototype", 0, 20)); // NOI18N
        l6.setForeground(new java.awt.Color(34, 54, 113));
        l6.setText("Number of members :");

        l2.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(34, 54, 113));
        l2.setText("THE DAY of Meeting is :");

        jLabel4.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 54, 113));
        jLabel4.setText("THE DAY of Meeting is the:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 57, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l11)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(l2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dia1Layout = new javax.swing.GroupLayout(dia1.getContentPane());
        dia1.getContentPane().setLayout(dia1Layout);
        dia1Layout.setHorizontalGroup(
            dia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dia1Layout.setVerticalGroup(
            dia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 54, 113));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libr/Digimon-logos_transparent.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search for a CLUB");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2))
        );

        reslist.setFont(new java.awt.Font("Prototype", 0, 28)); // NOI18N
        reslist.setForeground(new java.awt.Color(34, 54, 113));
        reslist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(reslist);

        jLabel8.setFont(new java.awt.Font("Prototype", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 54, 113));
        jLabel8.setText("Results :");

        jLabel3.setFont(new java.awt.Font("Prototype", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 54, 113));
        jLabel3.setText("Search By :");

        s.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLUB's Name", "BOOK's Name", "BOOK's ID" }));

        b.setBackground(new java.awt.Color(34, 54, 113));
        b.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        b.setForeground(new java.awt.Color(255, 255, 255));
        b.setText("Search");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        sb.setFont(new java.awt.Font("Prototype", 0, 18)); // NOI18N

        Bclubinfo.setBackground(new java.awt.Color(34, 54, 113));
        Bclubinfo.setFont(new java.awt.Font("Prototype", 0, 36)); // NOI18N
        Bclubinfo.setForeground(new java.awt.Color(255, 255, 255));
        Bclubinfo.setText("Show CLUB's Info");
        Bclubinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BclubinfoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(34, 54, 113));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Prototype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FAN CLUB MENU");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Bclubinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(s, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(Bclubinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BclubinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BclubinfoActionPerformed
        if(co == 0){
            JOptionPane.showMessageDialog(this, "NO RESULT IS SELECTED","ERROR",2);
        }else{
            dia1.setVisible(true);
            dia1.setBounds(500, 200, 910, 400);
            try {
                st = c.prepareStatement("SELECT books.BOOK_NAME, books.BOOK_ID,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.RATING,fanclub.CLUB_ID,fanclub.CLUB_NAME,fanclub.BOOK,fanclub.CLUB_ADMIN,fanclub.ADMIN_ID,members.MEMBER_EMAIL ,members.MEMBER_NAME,fanclub.M_DATE FROM fanclub,members,books,book_type,book_author,book_publisher WHERE CLUB_ID=? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID)  AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) AND (fanclub.ADMIN_ID=members.MEMBER_ID) AND (fanclub.BOOK=books.BOOK_ID) ORDER BY CLUB_ID");
                st.setString(1, bidi.get(reslist.getSelectedIndex()));
                rs = st.executeQuery();
                while(rs.next()){
                    int n = 0;
                    l1.setText("The CLUB's Name : " + rs.getString("CLUB_NAME"));
                    if(Integer.parseInt(rs.getString("M_DATE")) == 1){
                    l2.setText(rs.getString("M_DATE")+"st Day of Every Month");
                    }else if(Integer.parseInt(rs.getString("M_DATE")) == 2){
                    l2.setText(rs.getString("M_DATE")+"nd Day of Every Month");  
                    }else if(Integer.parseInt(rs.getString("M_DATE")) == 3){
                    l2.setText(rs.getString("M_DATE")+"rd Day of Every Month"); 
                    }else{
                    l2.setText(rs.getString("M_DATE")+"th Day of Every Month");    
                    }
                    l3.setText("The CLUB's Admin : " + rs.getString("MEMBER_NAME"));
                    String cid = rs.getString("CLUB_ID");
                    l5.setText("The Admin's E-mail : " + rs.getString("MEMBER_EMAIL"));
                    // l6.setText("The Number of members is : " + rs.getString("BOOK_STOCK"));
                    l7.setText("The BOOK's Name : " + rs.getString("books.BOOK_NAME"));
                    l8.setText("The BOOK's ID : " + rs.getString("BOOK_ID"));
                    l9.setText("The BOOK's Author : " + rs.getString("AUTHOR"));
                    l10.setText("The BOOk's Publisher : " + rs.getString("PUBLISHER"));
                    l11.setText("The BOOK's Rating : " + rs.getString("RATING"));
                    l12.setText("The BOOk's Type : " + rs.getString("TYPE"));
                    st = c.prepareStatement("SELECT * FROM MEMBERS WHERE FAN_1 = ?");
                    st.setString(1, cid);
                    rs = st.executeQuery();
                    while(rs.next()){
                        n++;
                    }st = c.prepareStatement("SELECT * FROM MEMBERS WHERE FAN_2 = ?");
                    st.setString(1, cid);
                    rs = st.executeQuery();
                    while(rs.next()){
                        n++;
                    }st = c.prepareStatement("SELECT * FROM MEMBERS WHERE FAN_3 = ?");
                    st.setString(1, cid);
                    rs = st.executeQuery();
                    while(rs.next()){
                        n++;
                    }
                    l6.setText("Number of members : "+n);
                }
            } catch (SQLException ex) {
                Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_BclubinfoActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        if(s.getSelectedIndex() == 0){
        reslist.setModel(model1);
        model1.removeAllElements();
        bidi.clear();
      
        name = sb.getText();
        try {
            st = c.prepareStatement("SELECT  books.BOOK_ID,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.RATING,fanclub.CLUB_ID,fanclub.CLUB_NAME,fanclub.BOOK,fanclub.CLUB_ADMIN,fanclub.ADMIN_ID,members.MEMBER_EMAIL FROM fanclub,members,books,book_type,book_author,book_publisher WHERE CLUB_NAME=? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID)  AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) AND (fanclub.ADMIN_ID=members.MEMBER_ID) AND (fanclub.BOOK=books.BOOK_ID) ORDER BY CLUB_ID");
            
            st.setString(1, name);
            rs = st.executeQuery();
            co = 0;
            while(rs.next()){
                model1.addElement(rs.getString("CLUB_NAME"));
                bidi.add(co, rs.getString("CLUB_ID"));
                co++;
            }
            if(co==0){
                JOptionPane.showMessageDialog(this, "No Result!","NO RESULT",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(s.getSelectedIndex() == 1){
        reslist.setModel(model1);
        model1.removeAllElements();
        bidi.clear();
     
        name = sb.getText();
        try {
            st = c.prepareStatement("SELECT  books.BOOK_ID,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.RATING,fanclub.CLUB_ID,fanclub.CLUB_NAME,fanclub.BOOK,fanclub.CLUB_ADMIN,fanclub.ADMIN_ID,members.MEMBER_EMAIL FROM fanclub,members,books,book_type,book_author,book_publisher WHERE BOOK_NAME=? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID)  AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) AND (fanclub.ADMIN_ID=members.MEMBER_ID) AND (fanclub.BOOK=books.BOOK_ID) ORDER BY CLUB_ID");
            st.setString(1, name);
            rs = st.executeQuery();
            co = 0;
            while(rs.next()){
                model1.addElement(rs.getString("CLUB_NAME"));
                bidi.add(co, rs.getString("CLUB_ID"));
                co++;
            }
            if(co==0){
                JOptionPane.showMessageDialog(this, "No Result!","NO RESULT",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
        }  
        }else if(s.getSelectedIndex() == 2){
        reslist.setModel(model1);
        model1.removeAllElements();
        bidi.clear();
        try{
               Integer.parseInt(sb.getText());
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Enter the ID in Integers!","Error",2);
            }
        name = sb.getText();
        try {
           st = c.prepareStatement("SELECT  books.BOOK_ID,book_author.AUTHOR,book_type.TYPE,book_publisher.PUBLISHER,books.RATING,fanclub.CLUB_ID,fanclub.CLUB_NAME,fanclub.BOOK,fanclub.CLUB_ADMIN,fanclub.ADMIN_ID,members.MEMBER_EMAIL FROM fanclub,members,books,book_type,book_author,book_publisher WHERE BOOK_ID=? AND (books.BOOK_AUTHOR = book_author.AUTHOR_ID)  AND (books.BOOK_TYPE = book_type.TYPE_ID) AND (books.BOOK_PUBLISHER = book_publisher.PUBLISHER_ID) AND (fanclub.ADMIN_ID=members.MEMBER_ID) AND (fanclub.BOOK=books.BOOK_ID) ORDER BY CLUB_ID");
            
            st.setString(1, name);
            rs = st.executeQuery();
            co = 0;
            while(rs.next()){
                model1.addElement(rs.getString("CLUB_NAME"));
                bidi.add(co, rs.getString("CLUB_ID"));
                co++;
            }
            if(co==0){
                JOptionPane.showMessageDialog(this, "No Result!","NO RESULT",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(searchb.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_bActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        (fclub.sc).setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bclubinfo;
    private javax.swing.JButton b;
    private javax.swing.JDialog dia1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JList<String> reslist;
    private javax.swing.JComboBox<String> s;
    private javax.swing.JTextField sb;
    // End of variables declaration//GEN-END:variables
}
